# Generated by Django 2.2.2 on 2020-05-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200528_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(default='mobile.png', upload_to=''),
        ),
    ]
