# Generated by Django 2.2.2 on 2020-05-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200528_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='mobile.png', upload_to=''),
        ),
    ]
